on:
  push:
    branches: [main]
  repository_dispatch:
    types: [build_page]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - shell: bash
        run: |
          rm -rf content
      - name: Checkout vault repo
        uses: actions/checkout@v4
        with:
          repository: mahulst/obsidian-vault
          path: content
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - shell: bash
        run: |
          npm install
          npx quartz build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 13407e049c54d16fe2638517ab7c5172
          projectName: mahulst
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
